// نسخة خادمية من الأماكن الثابتة في التطبيق — يستخدمها مساعد "اسأل سند"
// (البيانات الكاملة مع الهواتف والروابط تبقى في index.html؛ هنا فقط ما يحتاجه الذكاء الاصطناعي)
// ملاحظة: عند تحديث بيانات الأماكن في index.html حدّث هذا الملف أيضاً
export const BASE_PLACES = [
  { id: 4, name: 'مستشفى البريمي الحكومي', cat: 'الصحة', type: 'مستشفى حكومي', area: 'البريمي', hours: '24 ساعة', status: '✅ مفتوح' },
  { id: 12, name: 'محطة وقود أوكيو OQ (OQ Fuel Station)', cat: 'السيارات', type: 'محطة وقود', area: 'مدخل البريمي', hours: '24 ساعة', status: '✅ متاح' },
  { id: 22, name: 'بلدية البريمي (Buraimi Municipality)', cat: 'جهات مهمة', type: 'بلدية', area: 'البريمي', hours: '7:30ص-2:30م', status: '✅ مفتوح' },
  { id: 23, name: 'شرطة البريمي', cat: 'جهات مهمة', type: 'أمن وشرطة', area: 'البريمي', hours: '24 ساعة', status: '✅ دائم' },
  { id: 24, name: 'بنك مسقط - البريمي', cat: 'جهات مهمة', type: 'بنك', area: 'البريمي', hours: '8ص-2م', status: '✅ مفتوح' },
  { id: 25, name: 'هيئة الكهرباء والمياه', cat: 'جهات مهمة', type: 'خدمات عامة', area: 'البريمي', hours: '7:30ص-2:30م', status: '✅ مفتوح' },
  { id: 101, name: "Buraimi National Park", cat: "السياحة والترفيه", type: "منتزه وطني", area: "البريمي", hours: "غير معروفة", status: "⭐ 4.2 قوقل" },
  { id: 102, name: "Al Misyal Park", cat: "السياحة والترفيه", type: "منتزه", area: "البريمي", hours: "غير معروفة", status: "⭐ 3.6 قوقل" },
  { id: 103, name: "منتزه الواحة", cat: "السياحة والترفيه", type: "منتزه", area: "البريمي", hours: "غير معروفة", status: "⭐ 3.9 قوقل" },
  { id: 104, name: "Family Park - Saraa Park", cat: "السياحة والترفيه", type: "منتزه عائلي", area: "صراء", hours: "غير معروفة", status: "⭐ 3.3 قوقل" },
  { id: 105, name: "Open Gymnastic Park", cat: "السياحة والترفيه", type: "ملعب رياضي مفتوح", area: "البريمي", hours: "غير معروفة", status: "⭐ 4.3 قوقل" },
  { id: 106, name: "Fun Games", cat: "السياحة والترفيه", type: "ألعاب وترفيه", area: "البريمي", hours: "غير معروفة", status: "⭐ 4 قوقل" },
  { id: 107, name: "New Sports Complex, Buraimi", cat: "السياحة والترفيه", type: "مجمع رياضي", area: "البريمي", hours: "غير معروفة", status: "⭐ 4.2 قوقل" },
  { id: 108, name: "Al Khandaq Fort", cat: "السياحة والترفيه", type: "قلعة تاريخية", area: "البريمي", hours: "غير معروفة", status: "⭐ 4.2 قوقل" },
  { id: 109, name: "Al Hillah Castle", cat: "السياحة والترفيه", type: "قلعة تاريخية", area: "البريمي", hours: "غير معروفة", status: "⭐ 4 قوقل" },
  { id: 110, name: "Falaj Saraa", cat: "السياحة والترفيه", type: "فلج تراثي", area: "صراء", hours: "غير معروفة", status: "⭐ 4.5 قوقل" },
  { id: 111, name: "Sultan Qaboos Grand Masjid", cat: "مساجد", type: "جامع", area: "البريمي", hours: "مفتوح لأوقات الصلاة", status: "⭐ 4.6 قوقل" },
  { id: 112, name: "Saeed bin Humaid Al Nuaimi Mosque", cat: "مساجد", type: "مسجد", area: "البريمي", hours: "مفتوح لأوقات الصلاة", status: "⭐ 4.5 قوقل" },
  { id: 113, name: "Abdul Aziz Al Qasimi Mosque", cat: "مساجد", type: "مسجد", area: "البريمي", hours: "مفتوح لأوقات الصلاة", status: "⭐ 4.6 قوقل" },
  { id: 114, name: "Sharia Mosque", cat: "مساجد", type: "مسجد", area: "البريمي", hours: "مفتوح لأوقات الصلاة", status: "⭐ 4.4 قوقل" },
  { id: 115, name: "جامع أبو بكر الصديق", cat: "مساجد", type: "جامع", area: "البريمي", hours: "مفتوح لأوقات الصلاة", status: "⭐ 4.5 قوقل" },
  { id: 116, name: "Masjid Al Alawi", cat: "مساجد", type: "مسجد", area: "البريمي", hours: "مفتوح لأوقات الصلاة", status: "⭐ 4.4 قوقل" },
  { id: 117, name: "Bin Karm Masjid", cat: "مساجد", type: "مسجد", area: "البريمي", hours: "مفتوح لأوقات الصلاة", status: "⭐ 5 قوقل" },
  { id: 118, name: "Klaitham Humaid Al Nuaimi Mosque", cat: "مساجد", type: "مسجد", area: "البريمي", hours: "مفتوح لأوقات الصلاة", status: "⭐ 4.5 قوقل" },
  { id: 119, name: "مسجد فاطمه سالم راشد المزروعي", cat: "مساجد", type: "مسجد", area: "البريمي", hours: "مفتوح لأوقات الصلاة", status: "⭐ 4.7 قوقل" },
  { id: 120, name: "Ghanem Mosque", cat: "مساجد", type: "مسجد", area: "البريمي", hours: "مفتوح لأوقات الصلاة", status: "⭐ 4.6 قوقل" },
  { id: 121, name: "Al Safa Hotel", cat: "السياحة والترفيه", type: "فندق", area: "البريمي", hours: "غير معروفة", status: "⭐ 3.9 قوقل" },
  { id: 122, name: "Buraimi Hotel", cat: "السياحة والترفيه", type: "فندق", area: "البريمي", hours: "غير معروفة", status: "⭐ 3.5 قوقل" },
  { id: 123, name: "Al Jimi Plaza Hotel", cat: "السياحة والترفيه", type: "فندق", area: "البريمي", hours: "غير معروفة", status: "⭐ 3.6 قوقل" },
  { id: 124, name: "Pearl Island Hotel Apartment", cat: "السياحة والترفيه", type: "شقق فندقية", area: "البريمي", hours: "غير معروفة", status: "⭐ 3.7 قوقل" },
  { id: 125, name: "Taj Al Arab Hotel", cat: "السياحة والترفيه", type: "فندق", area: "البريمي", hours: "غير معروفة", status: "⭐ 3.6 قوقل" },
  { id: 126, name: "Danat Alburaimi Modern Hotel Apartments", cat: "السياحة والترفيه", type: "شقق فندقية", area: "البريمي", hours: "غير معروفة", status: "⭐ 4.1 قوقل" },
  { id: 127, name: "Sama Al Buraimi Hotel", cat: "السياحة والترفيه", type: "فندق", area: "البريمي", hours: "غير معروفة", status: "⭐ 3.6 قوقل" },
  { id: 128, name: "الامان للشقق الفندقية", cat: "السياحة والترفيه", type: "شقق فندقية", area: "البريمي", hours: "غير معروفة", status: "⭐ 3.5 قوقل" },
  { id: 129, name: "فندق واحة البركة", cat: "السياحة والترفيه", type: "فندق", area: "البريمي", hours: "غير معروفة", status: "⭐ 3.3 قوقل" },
  { id: 130, name: "Golden Star Hotel", cat: "السياحة والترفيه", type: "فندق", area: "البريمي", hours: "غير معروفة", status: "⭐ 3.7 قوقل" },
  { id: 131, name: "Sultan Karak", cat: "المطاعم والمقاهي", type: "كرك وشاي", area: "البريمي", hours: "غير معروفة", status: "⭐ 4.2 قوقل" },
  { id: 132, name: "Nafhat Burger", cat: "المطاعم والمقاهي", type: "مطعم برجر", area: "البريمي", hours: "غير معروفة", status: "⭐ 4 قوقل" },
  { id: 133, name: "رمال ضنك", cat: "المطاعم والمقاهي", type: "مطعم", area: "البريمي", hours: "غير معروفة", status: "⭐ 4.2 قوقل" },
  { id: 134, name: "SEKKA77 Restaurant", cat: "المطاعم والمقاهي", type: "مطعم وكوفي", area: "البريمي", hours: "غير معروفة", status: "⭐ 4 قوقل" },
  { id: 135, name: "Line Cafe لاين كوفي", cat: "المطاعم والمقاهي", type: "كافيه", area: "البريمي", hours: "غير معروفة", status: "⭐ 4.3 قوقل" },
  { id: 136, name: "دار الكرك Dar Al Karak", cat: "المطاعم والمقاهي", type: "كرك وشاي", area: "البريمي", hours: "غير معروفة", status: "⭐ 3.6 قوقل" },
  { id: 137, name: "Al Wadi Al Akhdar Coffee Shop", cat: "المطاعم والمقاهي", type: "كوفي شوب", area: "البريمي", hours: "غير معروفة", status: "⭐ 3.9 قوقل" },
  { id: 138, name: "Chicken House Al Buraimi", cat: "المطاعم والمقاهي", type: "وجبات سريعة", area: "البريمي", hours: "غير معروفة", status: "⭐ 3.9 قوقل" },
  { id: 139, name: "Al Neyadi Modern Bakery", cat: "المطاعم والمقاهي", type: "مخبز", area: "البريمي", hours: "غير معروفة", status: "⭐ 4.2 قوقل" },
  { id: 140, name: "The M Sweets", cat: "المطاعم والمقاهي", type: "حلويات", area: "البريمي", hours: "غير معروفة", status: "⭐ 4.7 قوقل" },
  { id: 141, name: "Buraimi City Center", cat: "التسوق", type: "مركز تسوق", area: "البريمي", hours: "غير معروفة", status: "⭐ 4 قوقل" },
  { id: 142, name: "مدينة الهدايا", cat: "التسوق", type: "هدايا ومستلزمات", area: "البريمي", hours: "غير معروفة", status: "⭐ 4 قوقل" },
  { id: 143, name: "LuLu Hypermarket - Al Buraimi", cat: "التسوق", type: "هايبرماركت", area: "البريمي", hours: "غير معروفة", status: "⭐ 4.1 قوقل" },
  { id: 144, name: "AlAin Gift Market أسواق العين للهدايا", cat: "التسوق", type: "أسواق وهدايا", area: "البريمي", hours: "غير معروفة", status: "⭐ 4 قوقل" },
  { id: 145, name: "Souq Al Jau سوق الجو", cat: "التسوق", type: "سوق شعبي", area: "البريمي", hours: "غير معروفة", status: "⭐ 4.6 قوقل" },
  { id: 146, name: "Ms. Max", cat: "التسوق", type: "متجر متنوع", area: "البريمي", hours: "غير معروفة", status: "⭐ 4.2 قوقل" },
  { id: 147, name: "Day To Day Hypermarket", cat: "التسوق", type: "هايبرماركت", area: "البريمي", hours: "غير معروفة", status: "⭐ 4.2 قوقل" },
  { id: 148, name: "Al Midan Mall", cat: "التسوق", type: "مول", area: "البريمي", hours: "غير معروفة", status: "⭐ 3 قوقل" },
  { id: 149, name: "Mactel Electronics | الكترونيات ماكتيل", cat: "التسوق", type: "إلكترونيات", area: "البريمي", hours: "غير معروفة", status: "⭐ 5 قوقل" },
  { id: 150, name: "Muscle House Nutrition Store", cat: "التسوق", type: "مكملات غذائية", area: "البريمي", hours: "غير معروفة", status: "⭐ 5 قوقل" },
];
